config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  root "main#index"

  get "google_login" => "main#google_login"
  get "verification/:id" => "main#verification"
  post "verification/:id" => "main#verification"
  delete "logout" => "main#logout"

  get "app_offer/:app_offer" => "main#app_offer", as: "app_offer"
  post "app_offer/:app_offer" => "main#app_offer"

  get "refer" => "main#refer"
  post "refer" => "main#refer"

  get "referral" => "main#referral"
  post "referral" => "main#referral"

  get "profile" => "main#profile"

  get "/admin/dashboard" => "admin/dashboard#index"
  get "/admin" => "admin/login#new"
  post "/admin" => "admin/login#login"
  delete "/admin/logout" => "admin/login#logout"

  get "postback" => "main#postback"

  namespace :admin do
    resources :articles
    resources :app_banners
    resources :users
    resources :app_offers do
      resources :offer_events
    end
    resources :affiliates
    resources :referrers
    resources :postbacks
  end
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::AdminController
  before_action :authenticate_user!
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  layout "admin"

  def index
    if params[:q].present?
      query = "%#{params[:q]}%"
      @articles = Article.where("title LIKE :query", query: query).order(created_at: :desc).paginate(page: params[:page], per_page: 15)
    else
      @articles = Article.order(created_at: :desc).paginate(page: params[:page], per_page: 15)
    end
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to admin_articles_path, notice: "Article was successfully created."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to admin_articles_path, notice: "Article was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to admin_articles_path, notice: "Article was successfully deleted."
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :desc, :category, :image_url, :status, :highlighted, :published_at)
  end
end

app/views/admin/articles/edit.html.erb
<!-- Page Content -->
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <p id="notice" style="color:orange;"><%= notice %></p>
      <div class="col-lg-12 d-flex flex-row">
        <h2 class="page-header" style="margin: 10px 0 15px !important;">Edit Article</h2>
      </div>
      <%= form_with(model: @article, url: admin_article_path) do |form| %>
      <% if @article.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
        <ul>
          <% @article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
      <!-- /.row -->
      <div class="row">
        <div class="col-lg-12">
          <div class="panel panel-default">
            <div class="panel-heading">
              Article Form
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-lg-6">
                  <div class="form-group">
                    <label>Title</label>
                    <%= form.text_field :title, class: "form-control", placeholder: "Enter title", required: true %>
                  </div>
                  <div class="form-group">
                    <label>Description</label>
                    <%= form.text_area :desc, class: "form-control", placeholder: "Enter description" %>
                  </div>
                  <div class="form-group">
                    <label>Category</label>
                    <%= form.text_field :category, class: "form-control", placeholder: "Enter category" %>
                  </div>
                  <div class="form-group">
                    <label>Image URL</label>
                    <%= form.text_field :image_url, class: "form-control", placeholder: "Enter image URL", required: true %>
                  </div>
                  <div class="form-group">
                    <label>Published At</label>
                    <%= form.datetime_select :published_at ,class: "form-control" %>
                  </div>
                  <div class="form-group">
                    <label for="statusSelect">Status</label>
                    <%= form.select :status, [["Active", true], ["Inactive", false]],{} ,{class: "form-control", id: "statusSelect"} %>
                  </div>
                  <div class="form-group">
                    <label for="statusSelect">Hightlighted</label>
                    <%= form.select :highlighted, [["Active", true], ["Inactive", false]],{} ,{class: "form-control", id: "statusSelect"} %>
                  </div>
                  <div class="form-group">
                    <%= form.submit "Save", class: "btn btn-primary" %>
                    <%= link_to "Back", admin_articles_path, class: "btn btn-default" %>
                  </div>
                </div>
              </div>
              <!-- /.row (nested) -->
            </div>
            <!-- /.panel-body -->
          </div>
          <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
      </div>
      <!-- /.row -->
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/admin/articles/index.html.erb
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h2 class="page-header">Listing Articles</h2>
      </div>
      <div class="new" style="margin-bottom: 15px;">
        <%= link_to "New Article", new_admin_article_path, class: "btn btn-primary" %>
      </div>
      <div>
        <%= form_with(url: admin_articles_path, method: :get) do |f| %>
          <div class="form-group">
            <%= f.text_field :q, placeholder: "Search by Title", class: "form-control" %>
          </div>
        <% end %>
      </div>
      <div class="col-lg-12">
        <% if @articles.any? %>
          <table class="table table-responsive table-bordered">
            <thead>
              <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Category Name</th>
                <th>Status</th>
                <th>Image</th>
                <th>Published At</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              <% @articles.each do |article| %>
                <tr>
                  <td><%= article.id %></td>
                  <td><%= article.title[0,50]+"..." %></td>
                  <td><%= article.category %></td>
                  <td>  <% if article.status == false %>
                      <p>❌</p>
                    <% else %>
                      <p>✔️</p>
                    <% end %></td>
                  <td><img style="width:40px;" src="<%=article.try(:image_url)%>" onerror="this.onerror=null;this.src='https://cdn.pixabay.com/photo/2014/03/24/17/21/wrong-295503_640.png';" /></td>
                  <td><%= article.published_at %></td>
                  <td class="app-banner-action" style="display: flex;gap:5px;">
                    <%= link_to "Edit", edit_admin_article_path(article), class: "btn btn-warning" %>
                    <%= button_to "Delete", admin_article_path(article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= will_paginate @articles %>
        <% else %>
          <h1 class="text-center">No article found.</h1>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/articles/new.html.erb
<!-- Page Content -->
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <p id="notice" style="color:orange;"><%= notice %></p>
      <div class="col-lg-12 d-flex flex-row">
        <h2 class="page-header" style="margin: 10px 0 15px !important;">New Article</h2>
      </div>
      <%= form_with(model: @article, url: admin_articles_path) do |form| %>
        <% if @article.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
            <ul>
              <% @article.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <!-- /.row -->
        <div class="row">
          <div class="col-lg-12">
            <div class="panel panel-default">
              <div class="panel-heading">
                Article Form
              </div>
              <div class="panel-body">
                <div class="row">
                  <div class="col-lg-6">
                    <div class="form-group">
                      <label>Title</label>
                      <%= form.text_field :title, class: "form-control", placeholder: "Enter title", required: true %>
                    </div>
                    <div class="form-group">
                      <label>Description</label>
                      <%= form.text_area :desc, class: "form-control", placeholder: "Enter description" %>
                    </div>
                    <div class="form-group">
                      <label>Category</label>
                      <%= form.text_field :category, class: "form-control", placeholder: "Enter category" %>
                    </div>
                    <div class="form-group">
                      <label>Image URL</label>
                      <%= form.text_field :image_url, class: "form-control", placeholder: "Enter image URL", required: true %>
                    </div>
                    <div class="form-group">
                      <label>Published At</label>
                      <%= form.datetime_select :published_at ,class: "form-control" %>
                    </div>
                    <div class="form-group">
                      <label for="statusSelect">Status</label>
                      <%= form.select :status, [["Active", true], ["Inactive", false]],{} ,{class: "form-control", id: "statusSelect"} %>
                    </div>
                    <div class="form-group">
                      <label for="statusSelect">Hightlighted</label>
                      <%= form.select :highlighted, [["Active", true], ["Inactive", false]],{} ,{class: "form-control", id: "statusSelect"} %>
                    </div>
                    <div class="form-group">
                      <%= form.submit "Save", class: "btn btn-primary" %>
                      <%= link_to "Back", admin_articles_path, class: "btn btn-default" %>
                    </div>
                  </div>
                </div>
                <!-- /.row (nested) -->
              </div>
              <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
          </div>
          <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
      <% end %>
    </div>
  </div>
</div>
</div>