config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  root "main#index"

  get "google_login" => "main#google_login"
  get "verification/:id" => "main#verification"
  post "verification/:id" => "main#verification"
  delete "logout" => "main#logout"

  get "app_offer/:app_offer" => "main#app_offer", as: "app_offer"
  post "app_offer/:app_offer" => "main#app_offer"

  get "refer" => "main#refer"
  post "refer" => "main#refer"

  get "referral" => "main#referral"
  post "referral" => "main#referral"

  get "profile" => "main#profile"

  get "/admin/dashboard" => "admin/dashboard#index"
  get "/admin" => "admin/login#new"
  post "/admin" => "admin/login#login"
  delete "/admin/logout" => "admin/login#logout"

  get "postback" => "main#postback"

  namespace :admin do
    resources :articles
    resources :app_banners
    resources :users
    resources :app_offers do
      resources :offer_events
    end
    resources :affiliates
    resources :referrers
    resources :postbacks
  end
end

app/models/app_offer.rb
class AppOffer < ApplicationRecord
  has_many :offer_events, dependent: :destroy
  has_many :referrers, dependent: :destroy
  scope :active, -> { where(status: true).order(created_at: :desc) }
end

app/controllers/admin/app_offers_controller.rb
class Admin::AppOffersController < Admin::AdminController
  before_action :set_app_offer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  layout "admin"

  def index
    if params[:q].present?
      query = "%#{params[:q]}%"
      @app_offers = AppOffer.where("offer_name LIKE :query OR identifier LIKE :query", query: query).order(created_at: :desc).paginate(page: params[:page], per_page: 15)
    else
      @app_offers = AppOffer.all.paginate(page: params[:page], per_page: 15).order(created_at: :desc)
    end
  end

  def show
    @offer_events = OfferEvent.where(app_offer_id: @app_offer.id)
    @offer_event = OfferEvent.new
  end

  def new
    @app_offer = AppOffer.new
  end

  def edit
  end

  def create
    @app_offer = AppOffer.new(app_offer_params)
    if @app_offer.save
      redirect_to admin_app_offer_path(@app_offer), notice: "App Offer was successfully created."
    else
      render :new
    end
  end

  def update
    if @app_offer.update(app_offer_params)
      redirect_to admin_app_offer_path(@app_offer), notice: "App Offer was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @app_offer.destroy
    redirect_to admin_app_offers_url, notice: "App Offer was successfully destroyed."
  end

  private

  def set_app_offer
    @app_offer = AppOffer.find(params[:id])
  end

  def app_offer_params
    params.require(:app_offer).permit(:offer_name, :offer_amount, :status, :description, :daily_cap, :whatsapp_link, :insta_offer, :retention_offer, :event_offer, :identifier, :refer_amount, :image_url, :instructions, :action_url, :offer_priority)
  end
end

app/views/admin/app_offers/edit.html.erb
<!-- Page Content -->
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <p id="notice" style="color:orange;"><%= notice %></p>
      <div class="col-lg-12 d-flex flex-row">
        <h2 class="page-header" style="margin: 10px 0 15px !important;">Edit App Offer</h2>
      </div>
      <%= form_with(model: @app_offer, url: admin_app_offer_path, local: true) do |form| %>
        <% if @app_offer.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@app_offer.errors.count, "error") %> prohibited this app offer from being saved:</h2>
            <ul>
              <% @app_offer.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <!-- Form Fields Row -->
        <div class="row">
          <div class="col-lg-12">
            <div class="panel panel-default">
              <div class="panel-heading">
                App Offer Form
              </div>
              <div class="panel-body">
                <div class="row">
                  <div class="col-lg-6">
                    <div class="form-group">
                      <%= form.label :offer_name %>
                      <%= form.text_field :offer_name, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                      <%= form.label :offer_amount %>
                      <%= form.text_field :offer_amount, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                      <%= form.label :daily_cap %>
                      <%= form.text_field :daily_cap, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                      <%= form.label :whatsapp_link %>
                      <%= form.text_field :whatsapp_link, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                      <%= form.label :identifier %>
                      <%= form.text_field :identifier, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                      <%= form.label :refer_amount %>
                      <%= form.text_field :refer_amount, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                      <%= form.label :image_url %>
                      <%= form.text_field :image_url, class: 'form-control' %>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <%= form.label :description %>
                      <%= form.text_area :description, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                      <%= form.label :instructions %>
                      <%= form.text_area :instructions, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                      <%= form.label :action_url %>
                      <%= form.text_field :action_url, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                      <%= form.label :offer_priority %>
                      <%= form.number_field :offer_priority, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                      <%= form.label :status, 'Status' %>
                      <%= form.select :status, [['Active', true], ['Inactive', false]], {}, { class: 'form-control' } %>
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <%= form.submit 'Edit', class: 'btn btn-primary' %>
                  <%= link_to 'Back to List', admin_app_offers_path, class: 'btn btn-default' %>
                </div>
              </div>
            </div>
            <!-- /.row (nested) -->
          </div>
          <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
      </div>
      <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
  <% end %>
</div>
</div>
</div>

app/views/admin/app_offers/index.html.erb
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <p id="notice" style="color:orange;"><%= notice %></p>
      <div class="col-lg-12 d-flex flex-row">
        <h2 class="page-header" style="margin: 10px 0 15px !important;">Listing App Offers</h2>
      </div>
      <div style="margin-bottom:15px;">
        <%= link_to 'New App Offer', new_admin_app_offer_path, class: 'btn btn-primary ml-auto' %>
      </div>
      <div>
        <%= form_with(url: admin_app_offers_path, method: :get) do |f| %>
          <div class="form-group">
            <%= f.text_field :q, placeholder: "Search by Offer Name or Identifier", class: "form-control" %>
          </div>
        <% end %>
      </div>
      <% if @app_offers.present? %>
        <table class="table table-responsive table-bordered">
          <thead>
            <tr>
              <th>ID</th>
              <th>Offer Image</th>
              <th>Offer Name</th>
              <th>Offer Amount</th>
              <th>Status</th>
              <th>Identifier</th>
              <th>Pay Amt/Ref Amt</th>
              <th>Created At</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @app_offers.each do |app_offer| %>
              <tr>
                <td><%= app_offer.id %></td>
                <td><img style="width:30px;" src="<%=app_offer.try(:image_url)%>" onerror="this.onerror=null;this.src='https://cdn.pixabay.com/photo/2014/03/24/17/21/wrong-295503_640.png';" /></td>
                <td><%= app_offer.offer_name %></td>
                <td><%= app_offer.offer_amount %></td>
                <td><%= app_offer.status ? 'Active' : 'Inactive' %></td>
                <td><%= app_offer.identifier %></td>
                <td><%= app_offer.offer_amount %> / <%= app_offer.refer_amount %></td>
                <td><%= l(app_offer.created_at, format: :long) %></td>
                <td style="display:flex;gap:5px;">
                  <%= link_to 'Show', admin_app_offer_path(app_offer), class: 'btn btn-primary btn-sm' %>
                  <%= link_to 'Edit', edit_admin_app_offer_path(app_offer), class: 'btn btn-warning btn-sm' %>
                  <%= button_to 'Delete', admin_app_offer_path(app_offer), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= will_paginate @app_offers %>
      <% else %>
        <h1 class="text-center">No App Offers Found</h1>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/app_offers/new.html.erb
<!-- Page Content -->
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <p id="notice" style="color:orange;"><%= notice %></p>
      <div class="col-lg-12 d-flex flex-row">
        <h2 class="page-header" style="margin: 10px 0 15px !important;">New App Offer</h2>
      </div>
      <%= form_with(model: @app_offer, url: admin_app_offers_path, local: true) do |form| %>
        <% if @app_offer.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@app_offer.errors.count, "error") %> prohibited this app offer from being saved:</h2>
            <ul>
              <% @app_offer.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="row">
          <div class="col-lg-12">
            <div class="panel panel-default">
              <div class="panel-heading">
                App Offer Form
              </div>
              <div class="panel-body">
                <div class="row">
                  <div class="col-lg-6">
                    <div class="form-group">
                      <%= form.label :offer_name %>
                      <%= form.text_field :offer_name, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                      <%= form.label :offer_amount %>
                      <%= form.text_field :offer_amount, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                      <%= form.label :daily_cap %>
                      <%= form.text_field :daily_cap, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                      <%= form.label :whatsapp_link %>
                      <%= form.text_field :whatsapp_link, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                      <%= form.label :identifier %>
                      <%= form.text_field :identifier, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                      <%= form.label :refer_amount %>
                      <%= form.text_field :refer_amount, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                      <%= form.label :image_url %>
                      <%= form.text_field :image_url, class: 'form-control' %>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <%= form.label :description %>
                      <%= form.text_area :description, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                      <%= form.label :instructions %>
                      <%= form.text_area :instructions, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                      <%= form.label :action_url %>
                      <%= form.text_field :action_url, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                      <%= form.label :offer_priority %>
                      <%= form.number_field :offer_priority, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                      <%= form.label :status, 'Status' %>
                      <%= form.select :status, [['Active', true], ['Inactive', false]], {}, { class: 'form-control' } %>
                    </div>
                  </div>
                </div>
                <!-- Checkboxes Row -->
                <div class="row">
                  <div class="col-md-12">
                    <div class="form-group form-check-inline">
                      <%= form.label :insta_offer, class: 'form-check-label' %>
                      <%= form.check_box :insta_offer, class: 'form-check-input' %>
                      <%= form.label :retention_offer, class: 'form-check-label' %>
                      <%= form.check_box :retention_offer, class: 'form-check-input' %>
                      <%= form.label :event_offer, class: 'form-check-label' %>
                      <%= form.check_box :event_offer, class: 'form-check-input' %>
                    </div>
                  </div>
                </div>
                <!-- Form Buttons -->
                <div class="form-group">
                  <%= form.submit 'Create', class: 'btn btn-primary' %>
                  <%= link_to 'Back to List', admin_app_offers_path, class: 'btn btn-default' %>
                </div>
              </div>
            </div>
            <!-- /.row (nested) -->
          </div>
          <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
      </div>
      <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
  <% end %>
</div>
</div>
</div>

app/views/admin/app_offers/show.html.erb
<!-- Page Content -->
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <p id="notice" style="color:orange;"><%= notice %></p>
      <div class="col-lg-12 d-flex flex-row">
        <h2 class="page-header" style="margin: 10px 0 15px !important;">App Offer Details</h2>
      </div>
      <% if @app_offer.present? %>
        <!-- Basic Information Table -->
        <table class="table table-responsive table-bordered">
          <thead>
            <tr>
              <th>ID</th>
              <th>Offer Name</th>
              <th>Offer Amount</th>
              <th>Status</th>
              <th>Identifier</th>
              <th>Offer Priority</th>
              <th>Created At</th>
              <th>Updated At</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @app_offer.id %></td>
              <td><%= @app_offer.offer_name %></td>
              <td><%= @app_offer.offer_amount %></td>
              <td><%= @app_offer.status ? 'Active' : 'Inactive' %></td>
              <td><%= @app_offer.identifier %></td>
              <td><%= @app_offer.offer_priority %></td>
              <td><%= l(@app_offer.created_at, format: :long) %></td>
              <td><%= l(@app_offer.updated_at, format: :long) %></td>
            </tr>
          </tbody>
        </table>
        <!-- Links and Identifiers Table -->
        <table class="table table-responsive table-bordered">
          <thead>
            <tr>
              <th>WhatsApp Link</th>
              <th>Action URL</th>
              <th>Image URL</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @app_offer.whatsapp_link %></td>
              <td><%= @app_offer.action_url %></td>
              <td><img style="width:40px;" src="<%= @app_offer.try(:image_url) %>" onerror="this.onerror=null;this.src='https://cdn.pixabay.com/photo/2014/03/24/17/21/wrong-295503_640.png';" /></td>
            </tr>
          </tbody>
        </table>
        <!-- Offer Types Table -->
        <table class="table table-responsive table-bordered">
          <thead>
            <tr>
              <th>Instagram Offer</th>
              <th>Retention Offer</th>
              <th>Event Offer</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @app_offer.insta_offer ? 'Yes' : 'No' %></td>
              <td><%= @app_offer.retention_offer ? 'Yes' : 'No' %></td>
              <td><%= @app_offer.event_offer ? 'Yes' : 'No' %></td>
            </tr>
          </tbody>
        </table>
        <!-- Cap and Amounts Table -->
        <table class="table table-responsive table-bordered">
          <thead>
            <tr>
              <th>Daily Cap</th>
              <th>Refer Amount</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @app_offer.daily_cap %></td>
              <td><%= @app_offer.refer_amount %></td>
            </tr>
          </tbody>
        </table>
        <!-- Descriptions Table -->
        <table class="table table-responsive table-bordered">
          <thead>
            <tr>
              <th>Description</th>
              <th>Instructions</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @app_offer.description %></td>
              <td><%= @app_offer.instructions %></td>
            </tr>
          </tbody>
        </table>
        <!-- Add Event Button -->
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addEventModal" style="margin-bottom:15px;">
          Add Event
        </button>
        <!-- Add Event Modal -->
        <div class="modal fade" id="addEventModal" tabindex="-1" role="dialog" aria-labelledby="addEventLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="addEventLabel">New Offer Event</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <%= form_with(model: [@app_offer, @offer_event], url: admin_app_offer_offer_events_path(@app_offer), method: :post, local: true) do |form| %>
                  <div class="form-group">
                    <%= form.label :event_order %>
                    <%= form.number_field :event_order, class: "form-control" %>
                  </div>
                  <div class="form-group">
                    <%= form.label :event_title %>
                    <%= form.text_field :event_title, class: "form-control" %>
                  </div>
                  <div class="form-group">
                    <%= form.label :event_amount %>
                    <%= form.number_field :event_amount, class: "form-control" %>
                  </div>
                  <div class="form-group">
                    <%= form.label :pay_type %>
                    <%= form.select :pay_type,[["Auto"], ["Manual"]],{} ,class: "form-control" %>
                  </div>
                  <%= form.hidden_field :app_offer_id, value: @app_offer.id %>
                  <div class="modal-footer">
                    <%= form.submit "Create Event", class: "btn btn-primary" %>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <!-- Edit Event Modals -->
        <% @offer_events.each do |event| %>
          <div class="modal fade" id="editEventModal<%= event.id %>" tabindex="-1" role="dialog" aria-labelledby="editEventLabel<%= event.id %>" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="editEventLabel<%= event.id %>">Edit Offer Event</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <%= form_with(model: [@app_offer, event], url: admin_app_offer_offer_event_path(@app_offer, event), method: :patch, local: true) do |form| %>
                    <div class="form-group">
                      <%= form.label :event_title %>
                      <%= form.text_field :event_title, class: "form-control" %>
                    </div>
                    <div class="form-group">
                      <%= form.label :event_amount %>
                      <%= form.number_field :event_amount, class: "form-control" %>
                    </div>
                    <div class="form-group">
                      <%= form.label :pay_type %>
                      <%= form.select :pay_type,[["Auto"], ["Manual"]],{} ,class: "form-control" %>
                    </div>
                    <div class="form-group">
                      <%= form.label :event_order %>
                      <%= form.number_field :event_order, class: "form-control" %>
                    </div>
                    <%= form.hidden_field :app_offer_id, value: @app_offer.id %>
                    <div class="modal-footer">
                      <%= form.submit "Update Event", class: "btn btn-primary" %>
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
        <!-- Offer Events Table -->
        <% if @offer_events.present? %>
          <table class="table table-responsive table-bordered">
            <thead>
              <tr>
                <th>Event Order</th>
                <th>Event Title</th>
                <th>Payout</th>
                <th>Pay Type</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              <% @offer_events.each do |event| %>
                <tr>
                  <td><%= event.event_order %></td>
                  <td><%= event.event_title %></td>
                  <td><%= event.event_amount %></td>
                  <td><%= event.pay_type %></td>
                  <td class="app-banner-action" style="display: flex; gap: 5px;">
                    <%= link_to "Edit", "#", class: "btn btn-warning", data: { toggle: "modal", target: "#editEventModal#{event.id}" } %>
                    <%= button_to "Delete", admin_app_offer_offer_event_path(@app_offer, event), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% else %>
          <h1 class="not-found">No Offer Events Found</h1>
        <% end %>
      <% else %>
        <h1 class="not-found">App Offer Not Found</h1>
      <% end %>
    </div>
  </div>
</div>