config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  root "main#index"

  get "google_login" => "main#google_login"
  get "verification/:id" => "main#verification"
  post "verification/:id" => "main#verification"
  delete "logout" => "main#logout"

  get "app_offer/:app_offer" => "main#app_offer", as: "app_offer"
  post "app_offer/:app_offer" => "main#app_offer"

  get "refer" => "main#refer"
  post "refer" => "main#refer"

  get "referral" => "main#referral"
  post "referral" => "main#referral"

  get "profile" => "main#profile"

  get "/admin/dashboard" => "admin/dashboard#index"
  get "/admin" => "admin/login#new"
  post "/admin" => "admin/login#login"
  delete "/admin/logout" => "admin/login#logout"

  get "postback" => "main#postback"

  namespace :admin do
    resources :articles
    resources :app_banners
    resources :users
    resources :app_offers do
      resources :offer_events
    end
    resources :affiliates
    resources :referrers
    resources :postbacks
  end
end

app/models/affiliate.rb
class Affiliate < ApplicationRecord
  has_many :referrers, dependent: :destroy
end

app/controllers/admin/affiliates_controller.rb
class Admin::AffiliatesController < Admin::AdminController
  before_action :authenticate_user!
  before_action :set_affiliate, only: [:show]
  layout "admin"

  def index
    if params[:q].present?
      query = "%#{params[:q]}%"
      @affiliates = Affiliate.where("paytm_number LIKE :query OR upi_id LIKE :query OR click_id LIKE :query", query: query).order(created_at: :desc).paginate(page: params[:page], per_page: 15)
    else
      @affiliates = Affiliate.order(created_at: :desc).paginate(page: params[:page], per_page: 15)
    end
  end

  def show
  end

  private

  def set_affiliate
    @affiliate = Affiliate.find(params[:id])
  end
end

app/views/admin/affiliates/index.html.erb
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <p id="notice" style="color:orange;"><%= notice %></p>
      <div class="col-lg-12">
        <h2 class="page-header" style="margin: 10px 0 15px !important;">Listing Affiliates</h2>
      </div>
      <div>
        <%= form_with(url: admin_affiliates_path, method: :get) do |f| %>
          <div class="form-group">
            <%= f.text_field :q, placeholder: "Search by Paytm Number or Upi Id or Click Id", class: "form-control" %>
          </div>
        <% end %>
      </div>
      <% if @affiliates.present? %>
        <table class="table table-responsive table-bordered">
          <thead>
            <tr>
              <th>ID</th>
              <th>Paytm Number</th>
              <th>UPI ID</th>
              <th>Campaign Name</th>
              <th>Refer Code</th>
              <th>Click Id</th>
              <th>Referrers Count</th>
              <th>Created At</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @affiliates.each do |affiliate| %>
              <tr>
                <td><%= affiliate.id %></td>
                <td><%= affiliate.paytm_number %></td>
                <td><%= affiliate.upi_id %></td>
                <td><%= affiliate.campaign_name %></td>
                <td><%= affiliate.refer_code %></td>
                <td><%= affiliate.click_id %></td>
                <td><%= affiliate.referrers_count %></td>
                <td><%= affiliate.created_at.strftime("%d/%m/%y %I:%M:%p") %></td>
                <td>
                  <%= link_to 'Show', admin_affiliate_path(affiliate), class: 'btn btn-primary btn-sm' %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="pagination">
          <%= will_paginate @affiliates %>
        </div>
      <% else %>
        <h1 class="text-center">No Affiliates Found</h1>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/affiliates/show.html.erb
<!-- Page Content -->
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <p id="notice" style="color:orange;"><%= notice %></p>
      <div class="col-lg-12 d-flex flex-row">
        <h2 class="page-header" style="margin: 10px 0 15px !important;">Affiliate Details</h2>
      </div>
      <% if @affiliate.present? %>
        <table class="table table-responsive table-bordered">
          <thead>
            <tr>
              <th>ID</th>
              <th>Paytm Number</th>
              <th>UPI ID</th>
              <th>Campaign Name</th>
              <th>Refer Code</th>
              <th>Referrers Count</th>
              <th>Created At</th>
              <th>Updated At</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @affiliate.id %></td>
              <td><%= @affiliate.paytm_number %></td>
              <td><%= @affiliate.upi_id %></td>
              <td><%= @affiliate.campaign_name %></td>
              <td><%= @affiliate.refer_code %></td>
              <td><%= @affiliate.referrers_count %></td>
              <td><%= l(@affiliate.created_at, format: :long) %></td>
              <td><%= l(@affiliate.updated_at, format: :long) %></td>
            </tr>
          </tbody>
        </table>
      <% else %>
        <h1 class="not-found">Affiliate Not Found</h1>
      <% end %>
    </div>
  </div>
</div>