config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  root "main#index"

  get "google_login" => "main#google_login"
  get "verification/:id" => "main#verification"
  post "verification/:id" => "main#verification"
  delete "logout" => "main#logout"

  get "app_offer/:app_offer" => "main#app_offer", as: "app_offer"
  post "app_offer/:app_offer" => "main#app_offer"

  get "refer" => "main#refer"
  post "refer" => "main#refer"

  get "referral" => "main#referral"
  post "referral" => "main#referral"

  get "profile" => "main#profile"

  get "/admin/dashboard" => "admin/dashboard#index"
  get "/admin" => "admin/login#new"
  post "/admin" => "admin/login#login"
  delete "/admin/logout" => "admin/login#logout"

  get "postback" => "main#postback"

  namespace :admin do
    resources :articles
    resources :app_banners
    resources :users
    resources :app_offers do
      resources :offer_events
    end
    resources :affiliates
    resources :referrers
    resources :postbacks
  end
end

app/models/app_banner.rb
class AppBanner < ApplicationRecord
  scope :active, -> { where(status: true) }
end

app/controllers/admin/app_banners_controller.rb
module Admin
  class AppBannersController < Admin::AdminController
    before_action :authenticate_user!

    layout "admin"

    def index
      if params[:q].present?
        query = "%#{params[:q]}%"
        @appBanners = AppBanner.where("title LIKE :query", query: query).order(created_at: :desc).paginate(page: params[:page], per_page: 15)
      else
        @appBanners = AppBanner.all.order("id DESC").paginate(:page => params[:page], :per_page => 15)
      end
    end

    def show
      @appBanner = AppBanner.find_by(id: params[:id])
    end

    def new
      @appBanner = AppBanner.new
    end

    def create
      @appBanner = AppBanner.new(app_banner_params)
      if @appBanner.save
        redirect_to admin_app_banners_path
      else
        render :new
      end
    end

    def edit
      @appBanner = AppBanner.find_by(id: params[:id])
    end

    def update
      @appBanner = AppBanner.find_by(id: params[:id])
      if @appBanner.update(app_banner_params)
        redirect_to admin_app_banners_path
      else
        render :edit
      end
    end

    def destroy
      @appBanner = AppBanner.find_by(id: params[:id])
      @appBanner.destroy
      redirect_to admin_app_banners_path
    end

    private

    def app_banner_params
      params.require(:app_banner).permit(:image_url, :action_url, :status, :title)
    end
  end
end

app/views/admin/app_banners/edit.html.erb
<!-- Page Content -->
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <p id="notice" style="color:orange;"><%= notice %></p>
      <div class="col-lg-12 d-flex flex-row">
        <h2 class="page-header" style="margin: 10px 0 15px !important;">Edit App Banner</h2>
      </div>
      <%= form_with(model: @appBanner, url: admin_app_banner_path(@appBanner)) do |form| %>
        <% if @appBanner.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@appBanner.errors.count, "error") %> prohibited this app banner from being saved:</h2>
            <ul>
              <% @appBanner.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <!-- /.row -->
        <div class="row">
          <div class="col-lg-12">
            <div class="panel panel-default">
              <div class="panel-heading">
                App Banners Form
              </div>
              <div class="panel-body">
                <div class="row">
                  <div class="col-lg-6">
                    <div class="form-group">
                      <label>Title</label>
                      <%= form.text_field :title, class: "form-control", placeholder: "Enter title", required: true %>
                    </div>
                    <div class="form-group">
                      <label>Image Url</label>
                      <%= form.text_field :image_url, class: "form-control", placeholder: "Enter image url", required: true %>
                    </div>
                    <div class="form-group">
                      <label>Action Url</label>
                      <%= form.text_field :action_url, class: "form-control", placeholder: "Enter action url" %>
                    </div>
                    <div class="form-group">
                      <label for="selectOptions">Status</label>
                      <%= form.select :status, [["Active", true], ["Inactive", false]], {}, {class: "form-control ",id: "selectOptions"} %>
                    </div>
                  </div>
                  <!-- /.col-lg-6 (nested) -->
                  <div class="col-lg-6">
                    <div class="form-group">
                      <label>Created At</label>
                      <span class="form-control"><%= @appBanner.created_at %></span>
                    </div>
                    <div class="form-group">
                      <label>Updated At</label>
                      <span class="form-control"><%= @appBanner.updated_at %></span>
                    </div>
                    <div class="form-group">
                      <%= form.submit "Update", class: "btn btn-primary" %>
                      <%= link_to "Back", admin_app_banners_path, class: "btn btn-default" %>
                    </div>
                  </div>
                  <!-- /.col-lg-6 (nested) -->
                </div>
                <!-- /.row (nested) -->
              </div>
              <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
          </div>
          <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/admin/app_banners/index.html.erb
<!-- Page Content -->
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h2 class="page-header" style="margin: 10px 0 15px !important;">Listing App Banners</h2>
      </div>
      <div class="new" style="margin-bottom: 15px;">
        <%= link_to "New App Banner", new_admin_app_banner_path, class: "btn btn-primary" %>
      </div>
      <div>
        <%= form_with(url: admin_app_banners_path, method: :get) do |f| %>
          <div class="form-group">
            <%= f.text_field :q, placeholder: "Search by Title", class: "form-control" %>
          </div>
        <% end %>
      </div>
      <% if @appBanners.present? %>
        <table class="table table-responsive table-bordered">
          <thead>
            <tr>
              <th>Id</th>
              <th>Title</th>
              <th>Image Url</th>
              <th>Action Url</th>
              <th>Status</th>
              <th>Created At</th>
              <th>Updated At</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <% @appBanners.each do |banner| %>
              <tr>
                <td><%= banner.id %></td>
                <td><%= banner.title %></td>
                <td><img style="width:20px;" src="<%= banner.try(:image_url) %>" onerror="this.onerror=null;this.src='https://cdn.pixabay.com/photo/2014/03/24/17/21/wrong-295503_640.png';" /></td>
                <td><%= banner.action_url %></td>
                <td>
                  <% if banner.status == false %>
                    <p>❌</p>
                  <% else %>
                    <p>✔️</p>
                  <% end %>
                </td>
                <td><%= banner.created_at %></td>
                <td><%= banner.updated_at %></td>
                <td class="app-banner-action" style="display: flex;gap:5px;">
                  <%= link_to "Show", admin_app_banner_path(banner), class: "btn btn-primary" %>
                  <%= link_to "Edit", edit_admin_app_banner_path(banner), class: "btn btn-warning" %>
                  <%= button_to "Delete", admin_app_banner_path(banner), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= will_paginate @appBanners %>
      <% else %>
        <h1 class="text-center">No App banners Found</h1>
      <% end %>
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->

app/views/admin/app_banners/new.html.erb
<!-- Page Content -->
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <p id="notice" style="color:orange;"><%= notice %></p>
      <div class="col-lg-12 d-flex flex-row">
        <h2 class="page-header" style="margin: 10px 0 15px !important;">New App Banner</h2>
      </div>
      <%= form_with(model: @appBanner, url: admin_app_banners_path) do |form| %>
        <% if @appBanner.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@appBanner.errors.count, "error") %> prohibited this app banner from being saved:</h2>
            <ul>
              <% @appBanner.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <!-- /.row -->
        <div class="row">
          <div class="col-lg-12">
            <div class="panel panel-default">
              <div class="panel-heading">
                App Banners Form
              </div>
              <div class="panel-body">
                <div class="row">
                  <div class="col-lg-6">
                    <div class="form-group">
                      <label>Title</label>
                      <%= form.text_field :title, class: "form-control", placeholder: "Enter title", required: true %>
                    </div>
                    <div class="form-group">
                      <label>Image Url</label>
                      <%= form.text_field :image_url, class: "form-control", placeholder: "Enter image url", required: true %>
                    </div>
                    <div class="form-group">
                      <label>Action Url</label>
                      <%= form.text_field :action_url, class: "form-control", placeholder: "Enter action url" %>
                    </div>
                    <div class="form-group">
                      <label for="selectOptions">Status</label>
                      <%= form.select :status, [["Active", true], ["Inactive", false]], {}, {class: "form-control ",id: "selectOptions"} %>
                    </div>
                    <div class="form-group">
                      <%= form.submit "Create", class: "btn btn-primary" %>
                      <%= link_to "Back", admin_app_banners_path, class: "btn btn-default" %>
                    </div>
                  </div>
                </div>
                <!-- /.row (nested) -->
              </div>
              <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
          </div>
          <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/admin/app_banners/show.html.erb
<!-- Page Content -->
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <p id="notice" style="color: orange;"><%= notice %></p>
      <div class="col-lg-12">
        <h2 class="page-header" style="margin: 10px 0 15px !important;">Showing App Banner</h2>
      </div>

      <!-- App Banner Details Table -->
      <table class="table table-responsive table-bordered">
        <thead>
          <tr>
            <th>Id</th>
            <th>Image Url</th>
            <th>Action Url</th>
            <th>Status</th>
            <th>Created At</th>
            <th>Updated At</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @appBanner.id %></td>
             <td><img style="width:20px;" src="<%=@appBanner.try(:image_url)%>" onerror="this.onerror=null;this.src='https://cdn.pixabay.com/photo/2014/03/24/17/21/wrong-295503_640.png';" /></td>
            <td><%= @appBanner.action_url %></td>
            <td>
              <% if @appBanner.status == false %>
                ❌
              <% else %>
                ✔️
              <% end %>
            </td>
            <td><%= @appBanner.created_at %></td>
            <td><%= @appBanner.updated_at %></td>

          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>